### ISSUE TITLE
Guild Invites

### ISSUE THREAD

**Issue by mfranca0009** [NostraliaWoW/HybridCore#1]
Seems there are issues with guild invites being sent out to players. Players are not being put into the guild when they are being sent a invite and pressing "accept". If you try to invite the player again, It will say the character/player is already in the guild. It appears on smaller guilds there is no issue. I have also was hearing in guild chat on Centrelink that there was a invite sent out to a player but the player was unable to see the invite.

Forum report: https://nostralia.org/forums/viewtopic.php?f=35&t=425

**Comment by pjfry651** [comment]
Fixed. Guild member limit is 321. Some guilds were above this during the core switch which caused the error. Removing members until they were below 321 has fixed the issue.
