### ISSUE TITLE
Fear(CC effects) +Aggro

### ISSUE THREAD

**Issue by PathlessGiant** [NostraliaWoW/HybridCore#7]
When two or more players are fighting an enemy and the person with threat (the tank) is feared, the enemy loses all aggro to the tank until the fear is over - he then immediately returns to the tank.

If the person tanking a target is feared, the target should not lose aggro and start attacking the rest of the group.

**Comment by Nolin7777** [comment]
Are you sure?

**Comment by PathlessGiant** [comment]
https://youtu.be/oXFjVHqXCi0?t=3m22s seems I am wrong. :)
